### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rrmm02** [Cutleast/Mod-Manager-Migrator#2]
**Describe the bug**

**Error Message**
If there is an error message, paste it here with full traceback.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Wuerfelhusten** [comment]
You know, we will need more information. Using this, we cannot really help you.

**Comment by Wuerfelhusten** [comment]
Open a new changelog with more information
