### ISSUE TITLE
[BUG] Happened a error.

### ISSUE THREAD

**Issue by Abab-bk** [Cutleast/Mod-Manager-Migrator#3]
**Describe the bug**
This problem occurs when I select Add Source and click Next. I have configured the staging folder correctly.

**Error Message**
Traceback (most recent call last):
  File "E:\Other\MMM\dialogs.py", line 382, in finish
KeyError: 'game'

**To Reproduce**
1. Click on "Add source", select Vortex and click on "Next"
2. Select the staging folder of Vortex and click on "Done".
3. See error.

![QQ截图20230324182130](https://user-images.githubusercontent.com/55276676/227496238-37946f58-6617-4feb-8a90-8d3900cb63bc.png)

**Comment by Cutleast** [comment]
Ah, I see. I added a new string "game" to the localisations, but forgot the chinese one. In the repo, the chinese translation has this string. For a temporary fix, open the chinese .json under MMM\data\locales and add the string "game" to the bottom.
The next version (v1.03 will likely release this afternoon (UTC: 15-17h) and will fallback to the english strings if a localisation is outdated (in case of a missing string).
